// <auto-generated />
using LabManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726152645_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LabManagementAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$GpfHGgpLzXxbnoOYUMBcBel5Tku2e5TOSoxkJsTMN7qk0IZKM6p0y",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$xu7VtLwr8TCEb5URdSDJK.z79NmI0dz1GdAR0wcaHs34vErJGf75q",
                            Role = "Lab Manager",
                            Username = "manager"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$uzrvWlAkY.yfTv1WhNr.VuRy1N0xgVGnqBKQzBTk35IN7KGfCN3Kq",
                            Role = "Student",
                            Username = "sinhvien"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
